### ISSUE TITLE
Unsigned 0.10 kext will not load in Yosemite (10.10.0)

### ISSUE THREAD

**Issue by tyrotex** [kasbert/OS-X-SAT-SMART-Driver#31]
Thanks for making this driver available.
However, it appears Apple are no longer permitting unsigned kexts to be loaded in Yosemite, rather than just warning about it, as in Mavericks.  From my system.log:

```
kextutil -t /System/Library/Extensions/SATSMARTDriver.kext
Notice: /System/Library/Extensions/SATSMARTDriver.kext has debug properties set.
Diagnostics for /System/Library/Extensions/SATSMARTDriver.kext:
Code Signing Failure: not code signed
ERROR: invalid signature for fi.dungeon.driver.SATSMARTDriver, will not load
```

Is there any way we can get the driver working in Yosemite?

**Comment by thepen** [comment]
@alvernall wrote 
"I realize that imposes a small fee to obtain an Apple Developer ID, but am certain that could easily be offset from user donations for software as useful as this is."

The thing is, Apple is not credentialing developers or 3rd party manufacturers for kext signing, see http://www.cindori.org/trim-enabler-and-yosemite/ 

Curious, what's the basis for suggesting "only one manufacturer now recommends it, the rest having provided firmware solutions to accomplish the same thing."? All I've read suggests otherwise, TRIM helps all SSDs more or less. Specifically WRT write amplification.
http://www.cindori.org/trim-vs-garbage-collection/

":Why isn't it up to that manufacturer to provide the means of legally enabling it on OS X machines?" 
See above.

**Comment by alvarnell** [comment]
On Thu, Jan 01, 2015 at 04:00 PM, thepen wrote:
> @alvernall wrote 
> "I realize that imposes a small fee to obtain an Apple Developer ID, but am certain that could easily be offset from user donations for software as useful as this is."
> 
> The thing is, Apple is not credentialing developers or 3rd party manufacturers for kext signing, see http://www.cindori.org/trim-enabler-and-yosemite/
> 
I think you are misreading the article. Apple won’t credential "Trim Enabler" as their stated position is that "Trim may cause data corruption when used with third party SSD’s.” I don’t know whether I believe this or not, but still it’s Apple’s position.  I currently have about a dozen 3rd party extensions that Apple currently allows and as we know SATSMARTDriver.kext 0.8 and 0.9 have been whitelisted for now.
> Curious, what's the basis for suggesting "only one manufacturer now recommends it, the rest having provided firmware solutions to accomplish the same thing."? All I've read suggests otherwise, TRIM helps all SSDs more or less. Specifically WRT write amplification.
> http://www.cindori.org/trim-vs-garbage-collection/
> 
This is really off topic for kasbert’s list, so I would rather discuss it elsewhere, but my source for that statement was an interview with OWC founder and CEO Larry O’Connor where he responded to the question:

> Q: Did third-party SSD makers get any warning of this change?
> 
> With one exception, no third-party SSD maker promoted use of/included a TRIM enabler hack for their drives.
> 
See <http://www.zdnet.com/article/os-x-yosemite-and-third-party-ssds-heres-what-you-need-to-know/>


-Al-

**Comment by macuserguru** [comment]
But SATSMARTDriver.kext 0.10 or newer are not whitelisted :-(

**Comment by alvarnell** [comment]
On Fri, Jan 02, 2015 at 01:25 AM, macuserguru wrote:
> But SATSMARTDriver.kext 0.10 or newer are not whitelisted :-(
> 
Which takes us back to November 10 when that was pointed out to start this discussion. Most users don’t need 0.10, so why is this important to you?


-Al-
-- 
Al Varnell
Mountain View, CA

**Comment by macuserguru** [comment]
#0.10 is not important for me - #0.8 works well under 10.10.1 and my used external USB and FW devices. As far as I know, some new devices are not listed in Info_driver.plist

For #0.8 Info_driver.plist  5.491 Byte
for #0.10 Info_driver.plist 38.000 Byte
