### ISSUE TITLE
Incompatible with macOS 11.0.1 and Apple Silicon Mac

### ISSUE THREAD

**Issue by dukai1011** [kasbert/OS-X-SAT-SMART-Driver#64]
![CleanShot 2020-11-23 at 20 26 19@2x](https://user-images.githubusercontent.com/9975427/100039238-708f1100-2dca-11eb-80d1-dddc22d362f8.png)

Please see the attach screenshot, both the 0.8, 0.10 and 0.11 version doesn't work on Apple silicon M1 processor Mac.

**Comment by alvarnell** [comment]
Where did you obtain those copies? None of the ones on this site will ever work because they are unsigned. You must obtain them from DriveDx or SMART Utility or some other third party utility that signs those drivers.

**Comment by dukai1011** [comment]
You can bypass the the identified developer by hold the ctrl key to run the application.

**Comment by alvarnell** [comment]
Sure, but that won't allow the drivers to be used. There is no way to bypass the loading of an unsigned driver. Go to one of the utility sites I mentioned to download their signed versions for free.

**Comment by macuserguru** [comment]
For future development.
Gives a chance for USB S.M.A.R.T. driver without using kext? And could work it with the new mechanism "system extensions" too?

**Comment by alvarnell** [comment]
There has been no development effort here for years, so unless one of the drive utility developers or someone else wants to assume responsibility, there won't be any such future development.

**Comment by macuserguru** [comment]
I know that's not a part of this project! 
My question was a general one.
Is it at all possible to get the S.M.A.R.T. values of a USB hard disks with the new feature "system extensions"?
