### ISSUE TITLE
Unable to remove SATSMARTDriver.kext

### ISSUE THREAD

**Issue by redvwyahoocom** [kasbert/OS-X-SAT-SMART-Driver#69]
I have used the Terminal Command "sudo rm -r /Library/Extensions/SATSMARTDriver.kext" to remove SATSMARTDriver.kext, but receive the following error:   No such file or directory

Julien@juliens-imac ~ % sudo rm -r /Library/Extensions/SATSMARTDriver.kext
rm: /Library/Extensions/SATSMARTDriver.kext: No such file or directory
Julien@juliens-imac ~ % 

Screen shot below:

<img width="589" alt="Screen Shot 2021-04-09 at 3 22 36 PM" src="https://user-images.githubusercontent.com/82237116/114230689-746d9b00-9947-11eb-9e84-5a8b071bfce1.png">
<img width="589" alt="Screen Shot 2021-04-09 at 3 21 16 PM" src="https://user-images.githubusercontent.com/82237116/114230695-76375e80-9947-11eb-8706-aa164b8469b9.png">

I have also tried to drag this item to the trash, but since the file is grayed out that does not work.

How do I remove the file SATSMARTDriver?

**Comment by alvarnell** [comment]
I can't tell from your Find screenshot exactly where your SATSMART extensions are located or what version of macOS you are running, but until recently they were installed to /System/Library/Extensions/ which are SIP protected by the latest versions of macOS.

But if they are actually in /System/Library/Extensions/ in a SIP enabled macOS, then you must either disable SIP temporarily or remove them from Recovery.

**Comment by redvwyahoocom** [comment]
Could you provide how to disable SIP?

It is located in the path you listed.


Julien Antkies
***@***.***

**Comment by alvarnell** [comment]
First, let me just say that both methods will require you to boot into Recovery, so deleting them from there is faster but somewhat more dangerous if you happen to mistype a Terminal command.

Since Apple no longer publishes how to disable SIP, I'm reluctant to do so here, but a browser search will reveal several sources of printed and video instructions.

**Comment by redvwyahoocom** [comment]
I found the command, thank you.

Would leaving the file in place cause any issues?


Julien Antkies
***@***.***

**Comment by alvarnell** [comment]
I'm not aware of any issues that it might cause. I suspect it's like most chuff that gets left behind and simply takes up some small amount of disk space.

**Comment by redvwyahoocom** [comment]
Much appreciated.
